#cloud-config
package_update: true
package_upgrade: true

packages:
  - fail2ban
  - ufw

ssh_pwauth: false

runcmd:
  - curl -fsSL https://get.docker.com | sh
  - ufw allow ssh && ufw --force enable
  - systemctl enable fail2ban && systemctl start fail2ban
  - mkdir -p /opt/borg
